AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cfn Template for CodeDeploy app'
Parameters:
  Stage:
    AllowedValues:
      - test
      - prod
    ConstraintDescription: Must be a valid Stage
    Description: Application Stage
    Type: String
  PipelineStackName:
    Default: AWSLineMovementInfrastructurePipelineStack
    Type: String
    Description: 'The name of the associated Pipeline stack created'

Resources:
  GameEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: '${AWS::StackName}-GameEventsTable'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: GameEventIdentifier
          AttributeType: S
        - AttributeName: Timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: GameEventIdentifier
          KeyType: HASH
        - AttributeName: Timestamp
          KeyType: RANGE

  AWSLineMovementServiceLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-AWSLineMovementServiceLambda'
      Handler: com.awslinemovement.service.handler.LambdaEntryPoint
      MemorySize: 512
      Role:
        Fn::ImportValue: "LambdaRoleArnExport"
      Code:
        S3Bucket: "awslinemovementservice-lambda-src-code"
        S3Key: "LambdaCode"
      Runtime: java11
      Timeout: 100

  LambdaCronEventTrigger:
    Type: AWS::Events::Rule
    Properties:
      Description: Cron job to trigger Lambda every 5 minutes
      ScheduleExpression: rate(5 minutes)
      State: "ENABLED"
      Targets:
        -
          Arn: !GetAtt AWSLineMovementServiceLambda.Arn
          Id: "AWSLineMovementServiceLambda"
          Input: "{}"

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AWSLineMovementServiceLambda
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt LambdaCronEventTrigger.Arn

Outputs:
  GameEventsTableName:
    Value:
      Ref: GameEventsTable
  GameEventsTableArn:
    Value:
      Fn::GetAtt:
        - GameEventsTable
        - Arn